http {
    upstream all {
        # Nomes dos serviços/app containers no docker-compose
        server app1:80;
        server app2:80;
        server app3:80;
    }

    server {
        listen 4500;

        location / {
            proxy_pass http://all/;

            # Encaminhar informações do cliente para o backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

events {
    worker_connections 1024;
}
